export const PLATFORM_FEE_PERCENT = Number(process.env.NEXT_PUBLIC_PLATFORM_FEE_PERCENT ?? 10)

export const GRADING_COMPANIES = ["PSA", "BGS", "CGC", "SGC"] as const
export type GradingCompany = (typeof GRADING_COMPANIES)[number]

export const PSA_GRADES = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"] as const
export const BGS_GRADES = ["1", "1.5", "2", "2.5", "3", "3.5", "4", "4.5", "5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10"] as const

export const RAW_CONDITIONS = [
  "Mint",
  "Near Mint",
  "Lightly Played",
  "Moderately Played",
  "Heavily Played",
  "Damaged",
] as const
export type RawCondition = (typeof RAW_CONDITIONS)[number]

export const LISTING_CONDITIONS = ["Graded", "Raw"] as const
export type ListingCondition = (typeof LISTING_CONDITIONS)[number]

export const ORDER_STATUSES = [
  "pending",
  "payment_captured",
  "shipped",
  "delivered",
  "complete",
  "disputed",
  "refunded",
  "cancelled",
] as const

export const POKEMON_SETS = [
  "Base Set",
  "Jungle",
  "Fossil",
  "Base Set 2",
  "Team Rocket",
  "Gym Heroes",
  "Gym Challenge",
  "Neo Genesis",
  "Neo Discovery",
  "Neo Revelation",
  "Neo Destiny",
  "Legendary Collection",
  "Expedition",
  "Aquapolis",
  "Skyridge",
  "EX Ruby & Sapphire",
  "EX Sandstorm",
  "EX Dragon",
  "EX Team Magma vs Team Aqua",
  "EX Hidden Legends",
  "EX FireRed & LeafGreen",
  "EX Team Rocket Returns",
  "EX Deoxys",
  "EX Emerald",
  "EX Unseen Forces",
  "EX Delta Species",
  "EX Legend Maker",
  "EX Holon Phantoms",
  "EX Crystal Guardians",
  "EX Dragon Frontiers",
  "EX Power Keepers",
  "Diamond & Pearl",
  "Mysterious Treasures",
  "Secret Wonders",
  "Great Encounters",
  "Majestic Dawn",
  "Legends Awakened",
  "Stormfront",
  "Platinum",
  "Rising Rivals",
  "Supreme Victors",
  "Arceus",
  "HeartGold & SoulSilver",
  "Unleashed",
  "Undaunted",
  "Triumphant",
  "Call of Legends",
  "Black & White",
  "Emerging Powers",
  "Noble Victories",
  "Next Destinies",
  "Dark Explorers",
  "Dragons Exalted",
  "Boundaries Crossed",
  "Plasma Storm",
  "Plasma Freeze",
  "Plasma Blast",
  "Legendary Treasures",
  "XY",
  "Flashfire",
  "Furious Fists",
  "Phantom Forces",
  "Primal Clash",
  "Roaring Skies",
  "Ancient Origins",
  "BREAKthrough",
  "BREAKpoint",
  "Fates Collide",
  "Steam Siege",
  "Evolutions",
  "Sun & Moon",
  "Guardians Rising",
  "Burning Shadows",
  "Shining Legends",
  "Crimson Invasion",
  "Ultra Prism",
  "Forbidden Light",
  "Celestial Storm",
  "Dragon Majesty",
  "Lost Thunder",
  "Team Up",
  "Unbroken Bonds",
  "Unified Minds",
  "Hidden Fates",
  "Cosmic Eclipse",
  "Sword & Shield",
  "Rebel Clash",
  "Darkness Ablaze",
  "Champion's Path",
  "Vivid Voltage",
  "Shining Fates",
  "Battle Styles",
  "Chilling Reign",
  "Evolving Skies",
  "Celebrations",
  "Fusion Strike",
  "Brilliant Stars",
  "Astral Radiance",
  "Pokémon GO",
  "Lost Origin",
  "Silver Tempest",
  "Crown Zenith",
  "Scarlet & Violet",
  "Paldea Evolved",
  "Obsidian Flames",
  "Paradox Rift",
  "Paldean Fates",
  "Temporal Forces",
  "Twilight Masquerade",
  "Shrouded Fable",
  "Stellar Crown",
  "Surging Sparks",
  "Prismatic Evolutions",
] as const

export const CATEGORY_LINKS = [
  { label: "All Cards", href: "/browse" },
  { label: "Base Set", href: "/browse?set=Base+Set" },
  { label: "PSA Graded", href: "/browse?condition=Graded&grader=PSA" },
  { label: "BGS Graded", href: "/browse?condition=Graded&grader=BGS" },
  { label: "Vintage", href: "/browse?era=vintage" },
  { label: "Modern", href: "/browse?era=modern" },
  { label: "Deals", href: "/browse?sort=price_asc" },
  { label: "Recently Listed", href: "/browse?sort=newest" },
] as const
